### ISSUE TITLE
Problem with running the game server

### ISSUE THREAD

**Issue by delington** [jmckible/dominion#2]
I did as it was described in the readme file but when I was about to run rake server I got the following message and trace: 

LoadError: cannot load such file -- spec/rake/spectask
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
A:/Users/Ricsi/git/dominion/Rakefile:1:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'

**Comment by jmckible** [comment]
Hey @hoksaat-sze, thanks for digging up this old code. What strikes me is that I neglected to create a Gemfile for this project, which means you'll need to either have the old gems install locally, or update a bit of code. I suspect this was done with a very old rspec, so I'd start with changing the first few lines of the Rakefile to:

```
require 'rspec/core/rake_task'

task :default=>:spec
task :spec=>['spec:units']

RSpec::Core::RakeTask.new do |t|
  t.rspec_opts = ["-c", "-f progress", "-r ./spec/spec_helper.rb"]
  t.pattern = 'spec/**/*_spec.rb'
end
```

That should support more recent rspecs. Then you can install the `term-ansicolor` gem. After doing that, I was able to run `rake server`

Hope that helps.

**Comment by delington** [comment]
Hey, thank you for the help I'll try it, but now it realized for me that this is a 9 years old project already! Hehe. :)
